---
name: PluginA5t9ar
author: plug_mcpe
main: PluginA5t9ar/main
version: 1.0v
api: 3.0.0

commands:
  g1:
       description: set gamemode 1
  g0:
       description: set gamemode 0
  g2:
       description: set gamemode 2
      

